# Prometheus configuration for LegisSync observability
# Optimized for cost-effective monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "legisync_rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # LegisSync backend metrics
  - job_name: "legisync-backend"
    static_configs:
      - targets: ["host.docker.internal:8000"] # Main API endpoint
    scrape_interval: 10s
    metrics_path: "/metrics"

  # LegisSync main API health checks
  - job_name: "legisync-api"
    static_configs:
      - targets: ["host.docker.internal:8000"] # Main API endpoint
    metrics_path: "/health"
    scrape_interval: 30s

# Alerting rules for cost-effective monitoring
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
